### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by 0x8890** [0x8890/doc-tree#18]
google results turn up a yaoi manga so `docchi` is probably not the best name.

I did some googling around for "ast doc" and found this: https://github.com/jmoyers/ast-doc

which does exactly what this module does, though this is way more complete. fortunately the npm package `ast-doc` is not taken so maybe it's a good option.

**Comment by 0x8890** [comment]
now I think `doc-tree` would be good.

**Comment by onbjerg** [comment]
@0x8890 I like that better, sounds very much like docchi also.

**Comment by 0x8890** [comment]
Done https://github.com/0x8890/doc-tree/commit/1a609758cb396612bb906142fb945f086965069f
